FRONTEND and WORKER working properly (Windows version) - 10-27-25 Monday 1:41am
Note: For Christian's Window's machine and this specific branch 'vercelbranchtest'

HoopTuber\fastapi is now named HoopTuber\backend
to fix the error below:
ImportError: cannot import name 'FastAPI' from 'fastapi'
due to the folder named fastapi/ shadowing the installed fastapi package. Renaming the folder to backend/ solves this  error.

Updates to .env files and to .gitignore:
Therefore even the env files have been RENAMED as well to represent that name change.